Create database  store_db;
 
 use  store_db;
    
### 3. Functional Requirements (Task to do):

## 3.1 Sales Analysis
/*• Calculate total revenue generated by each store.*/

select 
s.store_name,
sum(oi.quantity * oi.list_price) as total_revenue
from orders o
join order_items oi on o.order_id = oi.order_id
join stores s on o.store_id = s.store_id
group by s.store_name
order by total_revenue desc;


/* • Identify top 5 best-selling products.*/
select 
p.product_name,
sum(oi.quantity) as total_sales
from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name
order by total_sales desc
limit 5;


/* • Calculate monthly sales trends to observe seasonality and growth.*/

select 
date_format(o.order_date,'%y-%m') as month,
sum(oi.quantity * oi.list_price) as monthly_sales
from orders o
join order_items oi on o.order_id = oi.order_id
group by month
order by month;


/* • Identify Top-Selling Product per Category */
select *
from (
select 
c.category_name,
p.product_name,
sum(oi.quantity) as total_sales,
rank() over(partition by c.category_name order by sum(oi.quantity) desc) as rnk
from order_items oi
join products p on oi.product_id = p.product_id
join categories c on p.category_id = c.category_id
group by c.category_name,p.product_name
) ranked
where rnk = 1;


/* • List of Products with Running Total of Sales */

select *
from (
select 
c.category_name,
p.product_name,
sum(oi.quantity) as total_sales,
rank() over(partition by c.category_name order by sum(oi.quantity) desc) as rnk
from order_items oi
join products p on oi.product_id = p.product_id
join categories c on p.category_id = c.category_id
group by c.category_name,p.product_name
) ranked
where rnk = 1;

#### 3.2 Customer Analysis
/* Identify customers with the highest purchases.*/
select 
customer_id,
sum(quantity * list_price) as total_spent
from orders o
join order_items oi 
on o.order_id = oi.order_id
group by customer_id
order by total_spent desc;

/* • Find customers who have not placed any orders. */
select 
c.customer_id,
concat(c.first_name,' ',c.last_name) as customer_name
from customers c
left join orders o 
on c.customer_id = o.customer_id
where o.order_id is null;

/* • Identify customers who have placed at least 3 orders and spent more than $ 25,000 */
select 
store_id,
sum(quantity * list_price) as total_revenue
from orders o
join order_items oi 
on o.order_id = oi.order_id
group by store_id;

#### 3.3 Inventory Management
/* • Identify low-stock products (below 50 items in inventory).*/
select 
product_name,
quantity
from stocks
join products using(product_id)
where quantity < 50;


#### 3.4 Employee Performance Analysis
/* • Identify the top 5 employees based on order transactions handled.*/
select 
concat(s.first_name,' ',s.last_name) as staff_name,
count(o.order_id) as orders_handled
from staffs s
join orders o on s.staff_id = o.staff_id
group by staff_name
order by orders_handled desc
limit 5;

 /* Identify staff members with the highest number of orders processed */
 select staff_id, count(order_id) as total_orders
from orders
group by staff_id
order by total_orders desc;
 
 
 /* • Rank Staff Based on Revenue Generated */
select 
concat(s.first_name,' ',s.last_name) as staff_name,
sum(oi.quantity * oi.list_price) as revenue,
rank() over(order by sum(oi.quantity * oi.list_price) desc) as staff_rank
from staffs s
join orders o on s.staff_id = o.staff_id
join order_items oi on o.order_id = oi.order_id
group by staff_name;

### 3.5 Advanced Reporting
/* • Rank products by sales volume. */
select product_id,total_sales,
rank() over(order by total_sales desc) as product_rank
from (select product_id,sum(quantity) as total_sales
from order_items
group by product_id
) t;


/* • Compare Monthly Sales with Previous Month. */
select month,sales,
lag(sales) over(order by month) as previous_month_sales
from (select 
date_format(order_date,'%y-%m') as month,
sum(quantity * list_price) as sales
from orders o join order_items oi on o.order_id = oi.order_id
group by month)  t;



/* • Assign Row Number to Orders by Each Customer. */
select product_id,total_sales,
rank() over(order by total_sales desc) as product_rank
from (select product_id,
sum(quantity) as total_sales
from order_items
group by product_id
)  t;




